### PR TITLE
Special ability notation

### PR DESCRIPTION
**Pull request by RabidOwlbear**
Adds a special ability field to the monster character sheet in between the xp award and treasure table fields.
Data entered is stored at data.details.specialAbilities on the monster character object.

### CODE REVIEW

**Comment by RabidOwlbear** [comment]
This is submitted for review, not necessarily for immediate implementation.

**Comment by RabidOwlbear** [comment]
Not sure if it added the template.json change correctly, Pretty sure It did, if so this should be all that is needed to implement the special abilities input

**Comment by anthonyronda** [comment]
Sorry for waiting so long on this. Pre-review I saw the test console logging and thought "I'll just add a commits to the branch to remove those." And yeah, I got distracted. Doing this now

**Comment by anthonyronda** [comment]
Reopened in #206 and merged. Thank you!

**Pull request closed without merging**
